### ISSUE TITLE
System.ArgumentOutOfRangeException when running cleanup of Nitrox/previous QMMin

### ISSUE THREAD

**Issue by smaitlx1** [SubnauticaModding/QModManager#196]
When running the QModManager installer, the "clean up after Nitrox and previous QMM installs" step results in the following error.  The installer reports success, but QMM fails to function.

Attempting to clean up Nitrox and previous QMM installs...
Path is unsafe! D:\Steam\steamapps\common\Subnautica\BepInEx\patchers\QModManager\../../..\Subnautica_Data\Managed
Path is unsafe! D:\Steam\steamapps\common\Subnautica\BepInEx\patchers\QModManager\../../..\Subnautica_Data\Managed
EXCEPTION CAUGHT!
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Mono.Cecil.PE.ImageReader.ReadDebugHeader()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at QModManager.CleanUp.Initialize(String gameRootDirectory, String managedDirectory)
   at QModManager.Executable.Main(String[] args)

**Comment by adin49** [comment]
it helped me to disable antivirus, still doesnt load qmods tough

**Comment by desperationfighter** [comment]
@adin49 
I recommen you to visit the Subnautica Discord Modding Server.
https://discord.gg/UpWuWwq there we can do a better error handling
